### ISSUE TITLE
Importer Fails

### ISSUE THREAD

**Issue by fireman0865** [scaleway/netbox-netprod-importer#40]
Hi dear ,I am trying to run the importer but get this 

How Can I solve it

![Capture](https://user-images.githubusercontent.com/3670561/80371870-1e146300-8882-11ea-8c0f-24cc4a4671e1.PNG)
 ?

**Comment by aruhier** [comment]
Hi,
Can you give me the model of your switch please?

**Comment by fireman0865** [comment]
Hi it is WS-C2960-48FPS-L CISCO
SWITCH IMAGE=C2960X-UNIVERSALK9-M
SW VERSION: 15.2

**Comment by fireman0865** [comment]
Yeah there was some problems with napalm but ii't is not napalm really but
a problem with netmiko .i have regulated it and now all is ok With netmiko
.i think the problem maybe come from our proxy which block it .
Cordially

Le mer. 29 avr. 2020 à 16:30, Anthony Ruhier <notifications@github.com> a
écrit :

**Comment by aruhier** [comment]
Ok, I'm closing this issue then.

Feel free to give some news if it confirms it was your proxy. I don't think it is, though, but more probably the parsing of the 2960's shell.
