### ISSUE TITLE
Add parsing for Arista EOS

### ISSUE THREAD

**Issue by ryanmerolle** [scaleway/netbox-netprod-importer#47]
I have not looked into the specific of the parsers yet, but I understand that at least form factor and parent LAG features require the additional parsers.

**Comment by aruhier** [comment]
Hi,
Thanks a lot for the feature request. Sadly I don't have any network infrastructure I can use as target to do some tests anymore, so adding new parsers will be tricky for me. Also, I don't think Scaleway has any interest into adding parsers for Arista devices.

If you want to add it, I can certainly review it, but it will still be tricky for me to test it. I'll still merge it if the code looks ok to me, though, but mark it explicitly as lacking some real tests in the documentation.
