### ISSUE TITLE
Error when polling device

### ISSUE THREAD

**Issue by bertleywjh** [scaleway/netbox-netprod-importer#48]
It's getting all the information from the device correctly, but seems to fail importing to the device into Netbox.

`ERROR: netbox_importer: Error when polling device Switch1: 404 Client Error: Not Found for url: http://127.0.0.1/api/dcim/_choices/?limit=50 --`

That url doesn't seem to exist when I try to browse to it.

**Comment by aruhier** [comment]
Hi,
Thanks for the bug report. I'm aware of the issue, I'll close this one to avoid duplicates. It's linked to #39.
