### ISSUE TITLE
Which version of Netbox I need to run importer properly

### ISSUE THREAD

**Issue by Kani999** [scaleway/netbox-netprod-importer#53]
Hello, I'm trying importer with netbox version **2.7.1**
But I ended up with error:
```
ERROR: netbox_importer: Error when polling device XXXXXX: Interface FastEthernet9/1 could not be created: 500 Server Error: Internal Server Error for URL: http://localhost:8000/api/dcim/interfaces/

<pre><strong>&lt;class &#39;django.db.utils.IntegrityError&#39;&gt;</strong><br />

null value in column mode violates not-null constraint

DETAIL:  Failing row contains (1, FastEthernet9/1, 100base-tx, f, asd, 1, ad, null, t, 1500, null, null, null, null, null, null, null).
```

Which says `mode` value cannot be null.

---
I just want to see how imported data into a netbox looks. 
Which version of Netbox should I  use to run importer without error? (versions > 2.8.0 does not work) and version 2.7.1 does not work for me either, because of DB error.

**Comment by aruhier** [comment]
Hi,
There was an issue in Netbox at one point, in the 2.7 branch, iirc. Try the last version of the 2.7 branch, the 2.7.12.

**Comment by Kani999** [comment]
Everything works fine with version 2.7.12
I'm closing the issue. Thank you.

---
@aruhier May I ask if there is any progress with versions 2.8 and higher? 
I'm trying to bypass the problem with _choices, but with no luck yet.

**Comment by aruhier** [comment]
> @aruhier May I ask if there is any progress with versions 2.8 and higher?
> I'm trying to bypass the problem with _choices, but with no luck yet.

@Kani999: Sure, no problem. I'm not working for Scaleway for almost 2 years and have no personal use of this project and python-netboxapi. I know from Scaleway that there's some current effort to work on that, and I'll definitely help by at least reviewing the PRs.

But on my side, I cannot give you any ETA.
